### ISSUE TITLE
uninitialized constant Mime::VOICE

### ISSUE THREAD

**Issue by ayb** [stevegraham/twilio-rb#18]
I'm using Rails 3.0.10 and trying to integrate this gem using the code examples you provided in the README.  However I keep running into an issue with the voice MIME type.  

I keep getting the following error:
NameError (uninitialized constant Mime::VOICE)

From what I can see it looks like the Railtie is not executing during the app initialization process, hence the Voice MIME type is not being added/recognized.

Is there something I need to add to my application.rb file in order to make this work?

**Comment by stevegraham** [comment]
which version of twilio-rb are you using?

**Comment by ayb** [comment]
0.4

**Comment by stevegraham** [comment]
there is no railtie in 0.4, it was introduced later. try the latest version 2.1.3. 

i just made a test rails app with rails 3.0.10 and twilio-rb 2.1.3 and everything works as expected.
