### ISSUE TITLE
In a Rails 3 app: "superclass mismatch for class Cookie (TypeError)"

### ISSUE THREAD

**Issue by fredlee** [stevegraham/twilio-rb#2]
Have you ever seen this before?

**Comment by stevegraham** [comment]
hey fred. no i haven't. did you install using gem install or did you clone and build the gem using the rake task?

also, if you have a stack trace could i have it please?

s

**Comment by fredlee** [comment]
If I remove the "CGI" require from the 1st line of twilio.rb, the error no longer occurs. It looks like doing this require in your gem is causing Rails to try to double require the same library. But, I'm really not sure what is going.

**Comment by fredlee** [comment]
I did a bundle install of your gem.

**Comment by fredlee** [comment]
Stack trace:

/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:279: warning: already initialized constant CR
/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:282: warning: already initialized constant LF
/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:285: warning: already initialized constant EOL
/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:287: warning: already initialized constant REVISION
/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:289: warning: already initialized constant NEEDS_BINMODE
/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:292: warning: already initialized constant PATH_SEPARATOR
/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:313: warning: already initialized constant HTTP_STATUS
/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:317: warning: already initialized constant RFC822_DAYS
/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:320: warning: already initialized constant RFC822_MONTHS
/Users/flee1/.rvm/rubies/ree-1.8.7-2010.02/lib/ruby/1.8/CGI.rb:774: superclass mismatch for class Cookie (TypeError)
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in `require'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:591:in`new_constants_in'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:225:in `load_dependency'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/activesupport-3.0.1/lib/active_support/dependencies.rb:239:in`require'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/twilio-rb-0.3.1/lib/twilio.rb:1
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/twilio-rb-0.3.1/lib/twilio.rb:1:in `each'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/twilio-rb-0.3.1/lib/twilio.rb:1
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/bundler-1.0.7/lib/bundler/runtime.rb:64:in`require'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/bundler-1.0.7/lib/bundler/runtime.rb:64:in `require'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/bundler-1.0.7/lib/bundler/runtime.rb:62:in`each'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/bundler-1.0.7/lib/bundler/runtime.rb:62:in `require'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/bundler-1.0.7/lib/bundler/runtime.rb:51:in`each'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/bundler-1.0.7/lib/bundler/runtime.rb:51:in `require'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/bundler-1.0.7/lib/bundler.rb:112:in`require'
    from /Users/flee1/code/captainu/showcase/config/application.rb:7
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/railties-3.0.1/lib/rails/commands.rb:21:in `require'
    from /Users/flee1/.rvm/gems/ree-1.8.7-2010.02@showcase/gems/railties-3.0.1/lib/rails/commands.rb:21
    from script/rails:6:in`require'
    from script/rails:6

**Comment by stevegraham** [comment]
is the require in caps. see commit https://github.com/stevegraham/twilio-rb/commit/5ba9d47a55878c387e2aa106fe5baa9b24e17946

i need to push an update to rubygems i think

**Comment by fredlee** [comment]
Yep. That was it!. I tried it in lower case. That worked.

**Comment by stevegraham** [comment]
excellent! :)

**Comment by fredlee** [comment]
Just did a fresh 'bundle install' with your 0.4 version. Everything seem good. Thanks.
