### ISSUE TITLE
Ability to change config after initial setup

### ISSUE THREAD

**Issue by ajsharp** [stevegraham/twilio-rb#26]
This code in `lib/twilio/config.rb` prevents this currently:

``` ruby
module Twilio
  module Config
    def setup(opts={}, &blk)
      if block_given?
        instance_eval &blk
        warn 'The block syntax for configuration is deprecated. Use an options hash instead, e.g. Twilio::Config.setup account_sid: "AC00000000000000000000000", auth_token: "xxxxxxxxxxxxxxxxxxx"'
      else
        opts.map do |k,v|
          const = k.to_s.upcase
          Twilio.const_set(const, v) unless Twilio.const_defined? const
        end
      end
    end
  end
end
```

@stevegraham Would you be open to a patch that enables this?

This functionality is helpful especially in tests where you need to enable to live creds to record a few API interactions (purchasing a number, for example), but you want to use test creds most of the time.

**Comment by stevegraham** [comment]
:+1: but I think the account_sid should probably be stored using something other than a constant to avoid warnings. maybe class instance variables with attr_accessors on the Twilio module metaclass?

**Comment by ajsharp** [comment]
@stevegraham yea exactly what i was thinking. I'll write up a patch and submit a PR. Thx much :)

**Comment by stevegraham** [comment]
or the config module. that might make more sense actually.

**Comment by stevegraham** [comment]
kewl

**Comment by ajsharp** [comment]
@stevegraham Just FYI, a lot of the code relies on a kind of clever const_missing error to make sure the account_sid and auth_token are set, so I'm going to have to change a decent amount of code and replace areas where the constants are hardcoded into strings and such.

The const_missing thing is here: https://github.com/stevegraham/twilio-rb/blob/master/lib/twilio-rb.rb#L11

Still cool with this solution?

**Comment by stevegraham** [comment]
yea, those errors could be raised in the getter methods if the ivar == nil. what do you think?

**Comment by ajsharp** [comment]
Yea, I think we're on the same page. Should have something in a minute...

**Comment by ajsharp** [comment]
@stevegraham was this similar to what you had in mind? https://github.com/ajsharp/twilio-rb/commit/d3be62ab986cb07c9ababdeb996061c8673cff73

**Comment by ajsharp** [comment]
Looks like it's a problem with the canned response data not matching up. Easy fix.

**Comment by stevegraham** [comment]
I was thinking something like this:

``` ruby
module Twilio
  module Config
    class << self
      attr_writer :account_sid, :auth_token

      def account_sid
        if @account_sid
          @account_sid
        else
          raise Twilio::ConfigurationError.new \
            "Cannot complete request. Please set account_sid with Twilio::Config.setup first!"
        end
      end

      def auth_token
        if @auth_token
          @auth_token
        else
          raise Twilio::ConfigurationError.new \
            "Cannot complete request. Please set auth_token with Twilio::Config.setup first!"
        end
      end
    end
  end
end
```

What do you think?

**Comment by ajsharp** [comment]
Much better. I'll change it :)
