### ISSUE TITLE
Requiring builder >= 3.2.2 breaks compatibility with rails 3.2

### ISSUE THREAD

**Issue by pschuegr** [stevegraham/twilio-rb#32]
Are there 3.2.2 specific features of builder that twilio-rb is using?  Rails 3.2 requires ~> 3.1.0.

https://github.com/rails/rails/blob/master/actionview/actionview.gemspec#L25

**Comment by athirn** [comment]
I'm using activerecord 3.x in a project and as a result, I have the same issue.  I tried to use an older version of twilio-rb but rubygems is reporting that they are no longer available.

**Comment by stevegraham** [comment]
You can change the version of builder and submit a PR. I will merge it. Thnx.
