### ISSUE TITLE
should API prevent sms exceeding max length?

### ISSUE THREAD

**Issue by jpwynn** [stevegraham/twilio-rb#4]
if the sms message you send via the gem is too long, the logs show: Twilio::APIError (Error #21605: Maximum body length is 160 characters)

while this obviously isnt an error in the gem per se, it might be a nice enhancement if the Sms Create method had an option to truncate rather than fail. Just a thought.

**Comment by stevegraham** [comment]
Thanks for the suggestion Pardner. Twilio::APIError is deliberately raised when the API responds with a 400..599 status code. I think this example is best handled by application code, e.g. using ActiveModel validations.

**Comment by jpwynn** [comment]
yep that makes sense.if we create that sample app ;) I can illustrate that.
