### ISSUE TITLE
if Twilio::IncomingPhoneNumber.create() when already in account shouldn't it throw error?

### ISSUE THREAD

**Issue by jpwynn** [stevegraham/twilio-rb#7]
Discovered today that we had a situation where we called 

Twilio::IncomingPhoneNumber.create :phone_number => this_phone,
        :voice_url => a_voice_url,
        :sms_url => a_sms_url,
        :status_callback => a_callback_url,
        :friendly_name => a_friendly_name

when the phone number already was in our account.

The result was that it seemed to ignore the voice and sms url parameters we were trying to write.

It seems that perhaps it ought to return an error or throw an exception rather than ignore the parameters passed to it?

**Comment by stevegraham** [comment]
twilio-rb is a api wrapper, i.e. it provides a ruby interface to a 3rd party api endpoint abstracting api requests and responses as ruby objects. what you describe doesn't seem to be a problem with the library in that twilio is not sending back an error response to this request, hence no exception is raised.
