### ISSUE TITLE
Twilio::IncomingPhoneNumber wildcarding doesn't work?

### ISSUE THREAD

**Issue by jpwynn** [stevegraham/twilio-rb#8]
in Heroku console:

p=Twilio::IncomingPhoneNumber.all :area_code => '510'

returns every phone number in our account, NOT just the 510 area code numbers

we also tried 
p=Twilio::IncomingPhoneNumber.all :phone_number => "510*" and several other wildcards and it failed to

also, if we do what the twilio api docs say and use a phone number as '+15101234567' it gives the error
Twilio::APIError: Error #: Invalid Pattern.

**Comment by stevegraham** [comment]
thanks for the report. this is now fixed in head.
